a = 12
b = 13
print("   ",bin(a)[2:])
print("and",bin(b)[2:])
print("-----------")
print("   ",bin(a&b)[2:])
print(" ")
print("  ",bin(a)[2:])
print("or",bin(b)[2:])
print("-----------")
print("  ",bin(a|b)[2:])
print(" ")
print("   ",bin(a)[2:])
print("xor",bin(b)[2:])
print("-----------")
print("   ",bin(a^b)[2:])
print(" ")
print("   ",bin(a)[2:])
print("    ",bin(1<<2)[2:])
print("   ",(a&(1<<2)).bit_count())